use_frameworks!

platform :ios, '15.0'

target 'vantiq-ui-ios_Example' do
  # pod 'vantiq-sdk-ios', '~> 1.6'
  # pod 'AppAuth', '~> 1.7.5'
  # pod 'JWT', '~> 2.2.0'
  # pod 'Base64', '~> 1.1.2'
  # pod 'vantiq-ui-ios', :path => '../'
  pod 'vantiq-ui-ios'
  pod 'Base64', :git => 'https://github.com/Vantiq/Base64.git', :tag => '1.2.1.2'
  pod 'JWT', :git => 'https://github.com/Vantiq/JWT.git', :tag => '2.2.0.3'
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
	  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "15.0"
    end
  end
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
