use_frameworks!

platform :ios, '12.0'

target 'vantiq-ui-ios_Example' do
  pod 'vantiq-sdk-ios', '~> 1.6'
  pod 'AppAuth', '~> 1.7.5'
  pod 'JWT', '~> 2.2.0'
  pod 'Base64', '~> 1.1.2'
  pod 'vantiq-ui-ios', :path => '../'

  target 'vantiq-ui-ios_Tests' do
    inherit! :search_paths
  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
	  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "12.0"
    end
  end
end
